# Generated by Django 3.1.3 on 2020-11-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20201119_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('courseid', models.IntegerField()),
                ('coursetitle', models.CharField(default='SOME STRING', max_length=500)),
                ('coursename', models.CharField(default='SOME STRING', max_length=500)),
                ('coursesectioncode', models.IntegerField()),
                ('coursedepartment', models.CharField(default='SOME STRING', max_length=500)),
                ('instructorfullname', models.CharField(default='SOME STRING', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='coursedepartment',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='courseid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='coursename',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='coursetitle',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='instructorfullname',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='studentid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
