# Generated by Django 3.1.3 on 2020-11-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20201123_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='gpa',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
