# Generated by Django 3.1.3 on 2020-11-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_auto_20201123_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='gpa',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
