# Generated by Django 3.1.3 on 2020-11-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('coursetitle', models.CharField(max_length=500)),
                ('coursename', models.TextField()),
                ('coursesectioncode', models.IntegerField()),
                ('coursedepartment', models.TextField()),
                ('instructorfullname', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='gpa',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
