# Generated by Django 3.1.3 on 2020-11-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20201122_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='studentid',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lastname',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
